package deptHeadCounter;

public enum DHCOutputStatus {
    WRONG_INPUT,
    INFORMATION,
    SAVE_PERSONNEL_INFO_SUCCESS,
    SAVE_PERSONNEL_INFO_FAIL,
    UPDATE_DEPT_COMPOSITION_SUCCESS,
    UPDATE_FAIL_DEPT_NOT_EXIST,
    UPDATE_FAIL_PARENT_NOT_ASSIGNED,
    UPDATE_FAIL_ALREADY_HAVE_PARENT,
    UPDATE_FAIL_CANNOT_ADD_OWN_CHILD,
    FORM_INFORMATION
}
