package deptHeadCounter;

public enum DHCStatus {
    SAVE_DEPT_COMPOSITION_SUCCESS,
    FAIL_DEPT_NOT_EXIST,
    FAIL_CHILD_IS_HIGHEST_DEPT,
    FAIL_PARENT_NOT_ASSIGNED,
    FAIL_ALREADY_HAVE_PARENT,
    CANNOT_ADD_OWN_CHILD
}
